<?xml version="1.0"?>
<!--
  Copyright 2020 Giuseppe Silano, University of Sannio in Benevento, Italy
  Copyright 2018 Emanuele Aucone, University of Sannio in Benevento, Italy
  Copyright 2018 Benjamin Rodriguez, MIT, USA
  Copyright 2018 Luigi Iannelli, University of Sannio in Benevento, Italy
  Copyright 2020 Ria Sonecha, MIT, USA

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
-->

<robot name="crazyflie2" xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:include filename="$(find rotors_description)/urdf/component_snippets.xacro" />
  <!-- Instantiate crazyflie2 "mechanics" -->
  <xacro:include filename="$(find rotors_description)/urdf/crazyflie2.xacro" />

  <!-- Instantiate a controller.  -->
  <xacro:controller_plugin_macro namespace="${namespace}" imu_sub_topic="imu" />

  <!-- Enable the MAVLink interface. It is useful for the HIL (Hardware-in-the-loop) tests -->
  <xacro:if value="$(arg enable_mavlink_interface)">
    <!-- Instantiate mavlink telemetry interface. -->
    <xacro:default_mavlink_interface namespace="${namespace}" imu_sub_topic="imu" rotor_count="4" />
  </xacro:if>

  <!-- Mount an MPU-9250 IMU if the state estimator is enabled, otherwise the virtual odometry sensor is used. -->
  <xacro:if value="$(arg enable_state_estimator)">
    <xacro:crazyflie2_imu namespace="${namespace}" parent_link="${namespace}/base_link" />
  </xacro:if>

  <!-- Mount an ideal IMU sensor if the mellinger controller is enabled, otherwise the virtual odometry sensor is used. -->
  <xacro:if value="$(arg enable_mellinger_controller)">
    <xacro:crazyflie2_imuIdeal namespace="${namespace}" parent_link="${namespace}/base_link" />
  </xacro:if>

  <!-- Mount a generic odometry sensor. -->
  <xacro:crazyflie2_odometry namespace="${namespace}" parent_link="${namespace}/base_link"  />

  <!-- Mount a generic odometry sensor employed as ground truth -->
  <xacro:if value="$(arg enable_ground_truth)">
    <xacro:ground_truth_imu_and_odometry namespace="${namespace}" parent_link="${namespace}/base_link" />
  </xacro:if>

  <xacro:if value="$(arg enable_logging)">
    <!-- Instantiate a logger -->
    <xacro:bag_plugin_macro
      namespace="${namespace}"
      bag_file="$(arg log_file)"
      rotor_velocity_slowdown_sim="${rotor_velocity_slowdown_sim}"
      wait_to_record_bag="$(arg wait_to_record_bag)" />
  </xacro:if>

  <!-- Mount a ventral camera-sensor(changed to normal cam) on the Firefly. -->
  <xacro:if value="$(arg enable_camera_sensor)">
     <xacro:camera_macro
      namespace="${namespace}/ventral_cam"
      parent_link="${namespace}/base_link"
      camera_suffix="nadir"
      frame_rate="20.0"
      horizontal_fov="2"
      image_width="752"
      image_height="480"
      image_format="R8G8B8"
      min_distance="0.02"
      max_distance="50"
      noise_mean="0.0"
      noise_stddev="0.007"
      enable_visual="true">
      <box size="0.005 0.005 0.002" />
      <origin xyz="0 0 ${-arm_length/4}" rpy="0 ${pi/2} 0" />
     </xacro:camera_macro>
  </xacro:if>

  <!-- Mount a frontal camera-sensor(changed to normal cam) on the Firefly. -->
  <xacro:if value="$(arg enable_camera_sensor)">
     <xacro:camera_macro
      namespace="${namespace}/frontal_cam"
      parent_link="${namespace}/base_link"
      camera_suffix="nadir"
      frame_rate="20.0"
      horizontal_fov="2"
      image_width="752"
      image_height="480"
      image_format="R8G8B8"
      min_distance="0.02"
      max_distance="50"
      noise_mean="0.0"
      noise_stddev="0.007"
      enable_visual="true">
      <box size="0.005 0.005 0.002" />
      <origin xyz="${7*(arm_length/10)} 0 0" rpy="0 0 0" />
     </xacro:camera_macro>
  </xacro:if>

</robot>
