<?xml version="1.0"?>

<robot name="iris" xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:include filename="$(find rotors_description)/urdf/component_snippets.xacro" />
  <!-- Instantiate iris "mechanics" -->
  <xacro:include filename="$(find rotors_description)/urdf/iris.xacro" />

  <!-- Instantiate a controller. -->
  <xacro:controller_plugin_macro namespace="${namespace}" imu_sub_topic="imu" />

  <xacro:if value="$(arg enable_mavlink_interface)">
    <!-- Instantiate mavlink telemetry interface. -->
    <xacro:default_mavlink_interface namespace="${namespace}" imu_sub_topic="imu" rotor_count="4" />
  </xacro:if>

  <!-- Mount an ADIS16448 IMU. -->
  <xacro:default_imu namespace="${namespace}" parent_link="${namespace}/base_link" />

  <xacro:if value="$(arg enable_ground_truth)">
    <xacro:ground_truth_imu_and_odometry namespace="${namespace}" parent_link="${namespace}/base_link" />
  </xacro:if>

  <xacro:if value="$(arg enable_logging)">
    <!-- Instantiate a logger -->
    <xacro:bag_plugin_macro
      namespace="${namespace}"
      bag_file="$(arg log_file)"
      rotor_velocity_slowdown_sim="${rotor_velocity_slowdown_sim}"
      wait_to_record_bag="$(arg wait_to_record_bag)" />
  </xacro:if>

  <!-- Mount a ventral camera-sensor(changed to normal cam) on the iris. -->
  <xacro:if value="$(arg enable_camera_sensor)">
     <xacro:camera_macro
      namespace="${namespace}/ventral_cam"
      parent_link="${namespace}/base_link"
      camera_suffix="nadir"
      frame_rate="20.0"
      horizontal_fov="2"
      image_width="752"
      image_height="480"
      image_format="R8G8B8"
      min_distance="0.02"
      max_distance="50"
      noise_mean="0.0"
      noise_stddev="0.007"
      enable_visual="true">
      <box size="0.005 0.005 0.002" />
      <origin xyz="0 0 ${-arm_length_front_y/5}" rpy="0 ${pi/2} 0" />
     </xacro:camera_macro>
  </xacro:if>

  <!-- Mount a frontal camera-sensor(changed to normal cam) on the iris. -->
  <xacro:if value="$(arg enable_camera_sensor)">
     <xacro:camera_macro
      namespace="${namespace}/frontal_cam"
      parent_link="${namespace}/base_link"
      camera_suffix="nadir"
      frame_rate="20.0"
      horizontal_fov="2"
      image_width="752"
      image_height="480"
      image_format="R8G8B8"
      min_distance="0.02"
      max_distance="50"
      noise_mean="0.0"
      noise_stddev="0.007"
      enable_visual="true">
      <box size="0.005 0.005 0.002" />
      <origin xyz="${7*(arm_length_front_y/10)} 0 0" rpy="0 0 0" />
     </xacro:camera_macro>
  </xacro:if>

  <!-- Mount a ventral VI-sensor on the Iris. -->
  <xacro:if value="$(arg enable_vi_sensor)">
     <xacro:vi_sensor_macro_without_visual
      namespace="${namespace}/vi_sensor_ventral"
      parent_link="${namespace}/base_link"
      enable_cameras="false"
      enable_depth="true"
      enable_ground_truth="true">
      <origin xyz="${7*(arm_length/25)} 0 ${-arm_length/4}" rpy="0 ${pi/2} 0" />
     </xacro:vi_sensor_macro_without_visual>
  </xacro:if>

  <!-- Mount a frontal VI-sensor on the Iris. -->
  <xacro:if value="$(arg enable_vi_sensor)">
     <xacro:vi_sensor_macro_without_visual
      namespace="${namespace}/vi_sensor_frontal"
      parent_link="${namespace}/base_link"
      enable_cameras="false"
      enable_depth="true"
      enable_ground_truth="true">
      <origin xyz="${7*(arm_length/10)} 0 ${-arm_length/9}" rpy="0 0 0" />
     </xacro:vi_sensor_macro_without_visual>
  </xacro:if>

</robot>

